# Generated by Django 4.1.7 on 2023-03-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_category_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='un_categorized', on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='post.category'),
        ),
    ]
