# Generated by Django 4.1.7 on 2023-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
