# Generated by Django 4.1.7 on 2023-02-27 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='request_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='author',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
