# Generated by Django 4.1.7 on 2023-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_counter', '0003_alter_pagevisit_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='session',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session_key',
            field=models.CharField(default='1', max_length=350),
        ),
    ]
