# Generated by Django 4.1.7 on 2023-03-08 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit_counter', '0005_alter_pagevisit_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
