# Generated by Django 4.1.7 on 2023-03-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_counter', '0007_alter_pagevisit_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='user_id',
        ),
    ]
