# Generated by Django 4.1.7 on 2023-03-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_counter', '0009_pagevisit_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
