# Generated by Django 4.1.7 on 2023-03-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_counter', '0010_alter_pagevisit_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
