# Generated by Django 4.1.7 on 2023-03-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visit_counter', '0011_delete_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=100)),
                ('session_key', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=250)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PageVisit',
                'verbose_name_plural': 'PageVisit',
            },
        ),
    ]
